version: '2'
services:

  spark:
    image: gettyimages/spark
    volumes:
      - "./spark:/opt/spark"
    ports:
      - 8000:8000
      - 8080:8080
      - 8081:8081
      - 8088:8088
      - 8042:8042
      - 4040:4040

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
